### ISSUE TITLE
Multiple things not translated

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MIUI9-XML-DUTCH#153]
see pictures https://drive.google.com/folderview?id=1OZRMqi1OWkQ6ill4MoGixAkEmBgUd1T8

Mi6 latest stable version

**Comment by Cueie** [comment]
Dat kan er moet nog veel vertaald worden en momenteel doe ik dat alleen.
Heb dus een beetje tijd nodig om alles bij te houden

**Comment by x2tharay** [comment]
Is goed hoor geen probleem. Ik kan anders misschien wel helpen ik heb er alleen geen ervaring mee. Is het erg ingewikkeld?

**Comment by fordrwd4ever** [comment]
Misschien hoort dit hier niet, maar de link die Accuweather opent is verkeerd.

Als je de "en/nl" vervangt door "nl/nl" is deze wel netjes in het nederlands.

**Comment by dewingerd** [comment]
Had Miui 9 8.4.26 op mijn Mi Mix 2 staan. Alles was volledig vertaald in het nederlands. Na het installeren van Miui 10 8.6.14 blijft het meeste in het engels staan.

**Comment by redmaner** [comment]
Aan MIUI10 wordt gewerkt
