### ISSUE TITLE
Meerdere vertalingen missen en crash email app

### ISSUE THREAD

**Issue by monsieurpaulu** [redmaner/MIUI9-XML-DUTCH#16]
Mis afgelopen versies meerdere vertalingen zie foto's
![img_20170908_064521](https://user-images.githubusercontent.com/7716225/30196494-79bc1242-9461-11e7-87c3-9eabfaf814dc.png)
![screenshot_2017-09-08-06-39-46-146_com miui home](https://user-images.githubusercontent.com/7716225/30196495-79bd373a-9461-11e7-92db-391fd881f3b7.png)
![img_20170908_064435](https://user-images.githubusercontent.com/7716225/30196493-79ba67f8-9461-11e7-9e98-eee70a183798.png)

Verder crashes de email app
Wanneer je de knop links boven wil gebruiken , dit gebeurt niet in de engelse taal
![img_20170908_065111](https://user-images.githubusercontent.com/7716225/30196611-50394452-9462-11e7-9ce9-e1235a154618.png)

![screenshot_2017-09-08-06-38-12-391_com miui bugreport](https://user-images.githubusercontent.com/7716225/30196529-a66e3180-9461-11e7-9df9-d339e4e5701e.png)

Als ik ergens mee kan helpen hoor ik het graag

**Comment by MannyRibo** [comment]
Bedankt voor het melden. Wat betreft de missende vertalingen, deze zijn drie weken geleden allemaal al vertaald. Zijn de screenshots allemaal van 7.9.7 of van eerder? Dus of er is bij jou wat misgegaan of bij het ophalen van de vertalingen bij xiaomi.eu. Helaas is mijn telefoon net stuk dus kan ik het niet controleren of de vertalingen bij mij ook missen.

De force close van de email-app zal ik naar kijken.

**Comment by MannyRibo** [comment]
Als je de gegevens van de updaterapp wil wissen in de instellingen (cache + gegevens), de app opnieuw opent en kan kijken of de vertalingen nog steeds missen kan ik dat uitsluiten.

**Comment by MannyRibo** [comment]
Email app crash gevonden en hopelijk opgelost.

**Comment by monsieurpaulu** [comment]
Hallo , de screen shots zijn idd van 7.9.7 en heb net de cache en gegevens gewist maar dat mocht niet baten .
Heb overigens een mi5s

**Comment by MannyRibo** [comment]
Er bleek iets mis te zijn aan de kant van xiaomi.eu. Is nu opgelost dus volgende week zouden alle vertalingen weer helemaal volledig moeten zijn. Dankjewel
