### ISSUE TITLE
mu

### ISSUE THREAD

**Issue by jackb21** [redmaner/MIUI9-XML-DUTCH#17]
In  MIUI9-XML-DUTCH/Dutch/main/MiuiCamera.apk/res/values-nl/strings.xml  the image_file_name_format changed from 

`<string name="image_file_name_format">"'IMG'_yyyyMMdd_HHmmss"</string>`

`<string name="image_file_name_format">"'IMG'_ddMMyyyy_HHmmss"</string>` 

I think this change schould be reverted, so the files can be sorted correctly on their names.

Same goes for pano_file_name_format

**Comment by MannyRibo** [comment]
Why? What problems do you get with the current build?
