### ISSUE TITLE
Email app crashed 

### ISSUE THREAD

**Issue by monsieurpaulu** [redmaner/MIUI9-XML-DUTCH#23]
Ook onder miui 7.9.8 crashes de email app .
![30196611-50394452-9462-11e7-9ce9-e1235a154618](https://user-images.githubusercontent.com/7716225/30251930-ec5b1fd2-9669-11e7-8d21-42fdf6ba20ee.png)

**Comment by monsieurpaulu** [comment]
Tevens is de berichten app ook ineens  niet in het Nederlands maar volledig Engels

**Comment by MannyRibo** [comment]
Dat de FC nog niet is verholpen zou kunnen, de instelling zodat de vertalingen worden meegenomen in de rom zijn pas zaterdag gewijzigd. Vanaf de update naar MIUI 9 zijn er helemaal geen Nederlandse vertalingen in de rom verschenen dus ik ga er vanuit dat er veel meer niet vertaald is dan jij hier laat zien. 7.9.8 is is 7.9.7 met een fix, ik weet niet zeker of daarvoor opnieuw nieuwe vertalingen worden toegevoegd. Laten we volgende vrijdag kijken hoe en wat.

**Comment by monsieurpaulu** [comment]
In de laatste rom zijn de vertalingen wel mee gekomen , het gekke is alleen dat de berichten app ineens Engels is. 
We wachten tot vrijdag en zal dan laten weten als de problemen er dan nog zijn

**Comment by monsieurpaulu** [comment]
Hallo , 

Helaas in 7.9.14 nog steeds de email crach

**Comment by redmaner** [comment]
Hallo, 

Bedankt voor de feedback.

Deze crash is waarschijnlijk een variabel @MannyRibo, bijvoorbeeld %s of $1d of iets dergelijks dat verkeerd is of ontbreekt (alhoewel het ook iets anders kan zijn)

Ik ben zelf op vakantie, mocht het niet lukken kijk ik er over iets meer dan een weekje naar.

**Comment by MannyRibo** [comment]
Ik zal nogmaals kijken. Ik had even snel gekeken en zag alleen zo snel dat wat ik al heb gewijzigd (een regel teveel in arrays) dus ik ging er vanuit dat dat het was. Ik zal plurals en strings erbij pakken en vergelijken.

**Comment by KcNirvana** [comment]
@MannyRibo 
Hi,
I don't understand Dutch, so I don't know if problem solved.
But this line in Email.apk > strings.xml
  <string name="application_mime_type">applicatie/email-ls</string>
has to be removed because it causes FC.
In 
https://xiaomi.eu/community/threads/email-app-bug.41614/
https://xiaomi.eu/community/threads/7-9-14-15.41552/page-25#post-386822

Thank you

**Comment by MannyRibo** [comment]
Hi KcNirvana, 

No problem is not solved. I didn't really have the time yet. 
I will delete that string right away, thanks for cooperating.

**Comment by MannyRibo** [comment]
#29

**Comment by monsieurpaulu** [comment]
Probleem is opgelost bedankt !
