### ISSUE TITLE
Gedimde notificatie balk 

### ISSUE THREAD

**Issue by ikdedinges** [redmaner/MIUI9-XML-DUTCH#57]
Sinds .2 en nu met .9 heb ik op mn mi5splus een gedimde notificatie balk. De balk is pas weer normaal na een herstart.

**Comment by MannyRibo** [comment]
Ook als je telefoon op Engels staat?

**Comment by ikdedinges** [comment]
Weet ik niet, ga ik proberen

**Comment by MannyRibo** [comment]
Als dat het geval is kunnen wij er namelijk niks aan doen. Dan raad ik je aan om het te melden op het xiaomi.eu forum.

**Comment by ikdedinges** [comment]
Notificatie balk werd gelijk normaal na de taal aangepast te hebben.

**Comment by MannyRibo** [comment]
Heb je twee screenshots van hoe het eruit ziet als het 'gedimd' is en hoe het eruit ziet als hij op Engels staat?
