### ISSUE TITLE
Smart assistent is niet vertaald.

### ISSUE THREAD

**Issue by monsieurpaulu** [redmaner/MIUI9-XML-DUTCH#63]
Op mijn mi5s is voor de 3e rom op rij de smart assistent niet vertaald. 
![screenshot_2017-11-17-07-00-27-680_com miui home](https://user-images.githubusercontent.com/7716225/32931720-1054dd3e-cb66-11e7-869e-fcb8724304ba.png)
![screenshot_2017-11-17-07-02-27-210_com miui personalassistant](https://user-images.githubusercontent.com/7716225/32931721-107a0690-cb66-11e7-897c-1801f6f90ebc.png)

Bedankt voor jullie werk !

**Comment by MannyRibo** [comment]
Klopt. Hier ben ik niet aan toe gekomen vanwege tijdgebrek. Ik zal proberen vandaag een deel te doen.

**Comment by monsieurpaulu** [comment]
Oke  duidelijk ;)
Als je hulp nodig hebt met iets hoor ik het graag 

Paul

**Comment by MannyRibo** [comment]
We waren eerst met z'n drieën en sinds kort met z'n tweeën, waarbij ik hoofdzakelijk de vertalingen doe. Diegene die daar eerst mee hielp is sinds kort (even) gestopt maar heeft ook geen xiaomi telefoon meer dus dat die nog helpt kan ik heel erg waarderen. Zelf gebruik ik ook geen xiaomi meer op het moment maar ben van plan binnenkort een nieuwe telefoon te kopen waar ik dan een xiaomi zal nemen. Echter combineer ik sinds kort een baan met een studie dus je zult begrijpen dat ik niet altijd even veel tijd overhoud. Meestal kan ik goed bijblijven tenzij er dus opeens veel te vertalen is zoals met de smart assistant. Mocht je willen helpen zou dat altijd welkom zijn en worden gewaardeerd.

**Comment by monsieurpaulu** [comment]
Ik wil graag helpen , zeg maar hoe

**Comment by MannyRibo** [comment]
Ik zal vanavond contact met je opnemen, en ook de vertaling van smart assistant klaar hebben. https://github.com/redmaner/MIUI9-XML-DUTCH/commit/37b08afbe1cda36a3ce211333975e650833af440

**Comment by MannyRibo** [comment]
Smart assistant is compleet vertaald.
