### ISSUE TITLE
miui 9 stable not fully translated in Dutch

### ISSUE THREAD

**Issue by eric7325** [redmaner/MIUI9-XML-DUTCH#66]
Will miui 9 stable  be fully translated in Dutch ? For example the settings are still in English ....
Thanks for your work so far anyway

**Comment by redmaner** [comment]
Hello Eric,

The MIUI stable release has a less frequent release cycle, which means that sometimes the translation either lacks behind or is already more up to date than the release itself.

I assume that in the next stable release the translation will have made a big step, where elements previously untranslated are now translated.

If in the next update the translation still lacks behind in significant ways, please let us know and we'll look into it

**Comment by ingbrzy** [comment]
@eric7325  Could you post some screenshots where it is missing?

**Comment by eric7325** [comment]
![screenshot_2017-11-20-18-19-14-464_com android settings](https://user-images.githubusercontent.com/33806161/33031823-ac7a81f8-ce1f-11e7-97d4-106767da3fb6.png)

**Comment by eric7325** [comment]
Instellingen is still in English , some other like volume is in Dutch ...

**Comment by ingbrzy** [comment]
hm.. it should be translated already https://github.com/redmaner/MIUI9-XML-DUTCH/blob/master/Dutch/main/Settings.apk/res/values-nl/strings.xml#L5005

**Comment by eric7325** [comment]
Hmmm , ok . maybe reinstall ...

**Comment by MannyRibo** [comment]
Same with issue #60. Calculator seems completely translated to me. Is it  a problem on the user end or something else?

**Comment by redmaner** [comment]
@eric7325, which device are you using and which stable version are you running?

**Comment by eric7325** [comment]
Xiaomi Mi Max 2 and it is Miui 9 v9.0.1.0.NDDCNEI (stable) . Installed twice same result.

**Comment by eric7325** [comment]
As far as I can see , it is only the settings menu what is not translated ....
